# Generated by Django 4.2 on 2025-08-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApkFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('natco', models.CharField(max_length=50)),
                ('file_path', models.CharField(max_length=255)),
                ('upload_date', models.DateTimeField()),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apk_files',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApkInstallations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField()),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('job_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('result_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'apk_installations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Releases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_release', models.CharField(max_length=50)),
                ('sub_release', models.CharField(max_length=50)),
                ('box_release_info', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'releases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StbNodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(max_length=100)),
                ('natco', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stb_nodes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testcase_name', models.CharField(max_length=100)),
                ('functionality', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('testcase_number', models.CharField(max_length=100)),
                ('test_path', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'test_cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestExecutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_iterations', models.IntegerField(blank=True, null=True)),
                ('passed_iterations', models.IntegerField(blank=True, null=True)),
                ('failed_iterations', models.IntegerField(blank=True, null=True)),
                ('error_iterations', models.IntegerField(blank=True, null=True)),
                ('overall_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('natco', models.CharField(blank=True, max_length=50, null=True)),
                ('release_id', models.IntegerField(blank=True, null=True)),
                ('testcase_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_executions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TestIterations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration_number', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.CharField(max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('job_uid', models.CharField(blank=True, max_length=255, null=True)),
                ('result_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'test_iterations',
                'managed': False,
            },
        ),
    ]
