# Generated by Django 4.0 on 2025-02-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptissue',
            options={'ordering': ('-created',)},
        ),
    ]
