# Generated by Django 4.0 on 2025-02-25 04:34

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scriptissue_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TestcaseExcelResult',
        ),
        migrations.AddField(
            model_name='historicaltestcasemodel',
            name='steps',
            field=models.JSONField(default='', help_text='This is a Field to store all the Step Related to TestCase'),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='steps',
            field=models.JSONField(default='', help_text='This is a Field to store all the Step Related to TestCase'),
        ),
        migrations.DeleteModel(
            name='TestReport',
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='core.Tag'),
        ),
    ]
