# Generated by Django 4.0 on 2025-03-04 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tag_delete_testcaseexcelresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='natcosupport',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='natcosupport',
            name='language',
        ),
        migrations.RemoveField(
            model_name='natcosupport',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='natcosupport',
            name='natcos',
        ),
        migrations.RemoveField(
            model_name='natcosupport',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='natcosupport',
            name='testcase',
        ),
        migrations.RemoveField(
            model_name='natcosupport',
            name='user',
        ),
        migrations.DeleteModel(
            name='HistoricalNatcoSupport',
        ),
        migrations.DeleteModel(
            name='NatcoSupport',
        ),
    ]
