# Generated by Django 4.0 on 2025-03-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_natcosupport_devices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestcasemodel',
            name='steps',
            field=models.JSONField(blank=True, default='', help_text='This is a Field to store all the Step Related to TestCase', null=True),
        ),
        migrations.AlterField(
            model_name='testcasemodel',
            name='steps',
            field=models.JSONField(blank=True, default='', help_text='This is a Field to store all the Step Related to TestCase', null=True),
        ),
    ]
