# Generated by Django 4.0 on 2025-03-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historicaltestcasemodel_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestcasemodel',
            name='name',
            field=models.CharField(help_text='Please Enter the TestCase Name', max_length=255, verbose_name='Test Report Name'),
        ),
        migrations.AlterField(
            model_name='testcasemodel',
            name='name',
            field=models.CharField(help_text='Please Enter the TestCase Name', max_length=255, verbose_name='Test Report Name'),
        ),
    ]
