# Generated by Django 4.0 on 2025-03-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0006_alter_historicaltestcasemodel_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltestcasemodel',
            name='assigned',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='account.account', to_field='email'),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_testcase', to='account.account', to_field='email'),
        ),
    ]
