# Generated by Django 4.0 on 2025-03-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_historicaltestcasemodel_assigned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptissue',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scripts_issues', to='core.testcasescript'),
        ),
    ]
