# Generated by Django 4.0 on 2025-03-13 06:15

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('core', '0008_alter_scriptissue_script'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of TestPlan', max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
                ('testcases', models.ManyToManyField(related_name='test_plan_tests', to='core.TestCaseModel')),
            ],
            options={
                'verbose_name': 'Test Plan',
                'verbose_name_plural': 'Test Plans',
            },
        ),
    ]
