# Generated by Django 4.2.16 on 2025-04-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_testplan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltestcasemodel",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("class_1", "Class 1"),
                    ("class_2", "Class 2"),
                    ("class_3", "Class 3"),
                ],
                default="class_3",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="testcasemodel",
            name="priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("class_1", "Class 1"),
                    ("class_2", "Class 2"),
                    ("class_3", "Class 3"),
                ],
                default="class_3",
                max_length=20,
                null=True,
            ),
        ),
    ]
