# Generated by Django 5.1.7 on 2025-04-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_historicaltestcasemodel_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltestcasemodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testcasemodel',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testcasescript',
            name='script_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]