# Generated by Django 5.1.7 on 2025-04-09 13:46

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_historicaltestcasemodel_reporter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('priority', models.CharField(blank=True, choices=[('class_1', 'Class 1'), ('class_2', 'Class 2'), ('class_3', 'Class 3')], default='class_3', max_length=20, null=True)),
                ('testcase_type', models.CharField(choices=[('performance', 'Performance'), ('soak', 'Soak'), ('smoke', 'Smoke')], default='smoke', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('automation_status', models.CharField(choices=[('automatable', 'Automatable'), ('not-automatable', 'Not-Automatable'), ('in-development', 'In-Development'), ('review', 'Review'), ('ready', 'Ready'), ('completed', 'Complete')], default='not-automatable', max_length=100)),
                ('change_reason', models.CharField(blank=True, max_length=200, null=True)),
                ('changed_fields', models.JSONField(default='', max_length=200)),
                ('other_changes', models.JSONField(blank=True, default='', help_text='This is a Field to store all the Step Related to TestCase', null=True)),
                ('testcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.testcasemodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HistoricalTestCaseModel',
        ),
    ]