# Generated by Django 4.2 on 2025-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_testcasehistorymodel_delete_historicaltestcasemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcasehistorymodel',
            options={'verbose_name': 'TestCase History'},
        ),
        migrations.AlterField(
            model_name='testcasescript',
            name='script_location',
            field=models.URLField(max_length=300),
        ),
    ]