# Generated by Django 4.2 on 2025-04-15 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_alter_testcasehistorymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasescript',
            name='script_location',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='HistoricalTestCaseModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('jira_id', models.IntegerField(blank=True, db_index=True, help_text='Jira Id', null=True, verbose_name='Jira Id')),
                ('name', models.CharField(help_text='Please Enter the TestCase Name', max_length=255, verbose_name='Test Report Name')),
                ('priority', models.CharField(blank=True, choices=[('class_1', 'Class 1'), ('class_2', 'Class 2'), ('class_3', 'Class 3')], default='class_3', max_length=20, null=True)),
                ('summary', models.TextField(default='', verbose_name='Jira Summary')),
                ('description', models.TextField(default='', verbose_name='TestCase Description')),
                ('testcase_type', models.CharField(choices=[('performance', 'Performance'), ('soak', 'Soak'), ('smoke', 'Smoke')], default='smoke', max_length=20)),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('automation_status', models.CharField(choices=[('automatable', 'Automatable'), ('not-automatable', 'Not-Automatable'), ('in-development', 'In-Development'), ('review', 'Review'), ('ready', 'Ready'), ('completed', 'Complete')], default='not-automatable', max_length=100)),
                ('steps', models.JSONField(blank=True, default='', help_text='This is a Field to store all the Step Related to TestCase', null=True)),
                ('reporter', models.CharField(blank=True, max_length=200, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, to_field='email')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical TestCase',
                'verbose_name_plural': 'historical TestCases',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
