# Generated by Django 4.2 on 2025-04-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_testcasescript_script_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasescript',
            name='script_location',
            field=models.URLField(max_length=400),
        ),
    ]
