# Generated by Django 4.2 on 2025-04-22 07:04

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_historicaltestcasemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseJobId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('job_id', models.CharField(max_length=255)),
                ('testscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_id', to='core.testcasescript')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='HistoricalTestCaseModel',
        ),
    ]
