# Generated by Django 4.2 on 2025-04-22 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_testcasejobid_delete_historicaltestcasemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcasemodel',
            options={'ordering': ['-id'], 'permissions': (('can_change_status_to_review', 'Can Change Status to Review'), ('can_change_status_to_ready', 'Can Change Status to Ready')), 'verbose_name': 'TestCase', 'verbose_name_plural': 'TestCases'},
        ),
    ]
