# Generated by Django 4.2 on 2025-04-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_testcasemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testcasehistorymodel',
            options={'ordering': ('-created',)},
        ),
    ]
