# Generated by Django 4.2 on 2025-04-23 06:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_testcasehistorymodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comments',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='testcasemodel',
            name='description',
            field=ckeditor.fields.RichTextField(default='', help_text='Text Description'),
        ),
    ]
