# Generated by Django 4.0 on 2025-05-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_comment_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasescript',
            name='function_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
