# Generated by Django 4.0 on 2025-06-05 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_testcasescript_function_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasejobid',
            name='testscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_ids', to='core.testcasescript'),
        ),
    ]
