# Generated by Django 4.0 on 2025-06-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_testcasejobid_testscript'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasescript',
            name='job_ids',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TestCaseJobId',
        ),
    ]
