# Generated by Django 4.0 on 2025-06-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0016_alter_natcorelease_options_stbnodemapping'),
        ('core', '0025_testcasescript_job_ids_delete_testcasejobid'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcasescript',
            name='supported_natcos',
            field=models.ManyToManyField(blank=True, null=True, related_name='supported_natcos', to='stb.NatcoRelease'),
        ),
    ]
