# Generated by Django 4.2 on 2025-07-15 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_testcasescript_supported_natcos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCaseMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('likelihood', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('impact', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('priority', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('failure_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('failure', models.IntegerField(blank=True, default=0, null=True)),
                ('total_runs', models.IntegerField(blank=True, default=0, null=True)),
                ('direct_impact', models.CharField(blank=True, default='Yes', max_length=10, null=True)),
                ('defects', models.IntegerField(blank=True, default=0, null=True)),
                ('severity', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('feature_size', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('execution_time', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'TestCase MetaData',
                'verbose_name_plural': 'TestCase MetaData',
            },
        ),
        migrations.CreateModel(
            name='TestcaseTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='testcasemodel',
            name='jira_id',
            field=models.IntegerField(blank=True, help_text='Jira Id', null=True, verbose_name='Jira Id'),
        ),
        migrations.AlterField(
            model_name='testcasemodel',
            name='testcase_type',
            field=models.CharField(blank=True, choices=[('performance', 'Performance'), ('soak', 'Soak'), ('smoke', 'Smoke')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TestPlan',
        ),
        migrations.AddField(
            model_name='testcasemetadata',
            name='testcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='core.testcasemodel'),
        ),
        migrations.AddField(
            model_name='testcasemodel',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.module'),
        ),
    ]
