# Generated by Django 4.2 on 2025-07-15 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0027_module_testcasemetadata_testcasetypes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(help_text='Name of TestPlan', max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('priority', models.CharField(blank=True, choices=[('class_1', 'Class 1'), ('class_2', 'Class 2'), ('class_3', 'Class 3')], max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('todo', 'Todo'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=255, null=True)),
                ('output_count', models.IntegerField(blank=True, null=True, verbose_name='Output count')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('modules', models.ManyToManyField(blank=True, related_name='moduels', to='core.module')),
            ],
            options={
                'verbose_name': 'Test Plan',
                'verbose_name_plural': 'Test Plans',
            },
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('testscore', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4, null=True)),
                ('testcases', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='core.testcasemodel')),
                ('testplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='core.testplan')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testplan',
            name='testcases',
            field=models.ManyToManyField(through='core.TestScore', to='core.testcasemodel'),
        ),
    ]
