# Generated by Django 4.2 on 2025-07-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_testplan_testscore_testplan_testcases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcasemodel',
            name='testcase_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.testcasetypes', to_field='name'),
        ),
    ]
