# Generated by Django 4.0 on 2025-03-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_userlogs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLogs',
        ),
    ]
