# Generated by Django 4.2.16 on 2025-03-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("general", "0005_notification_content_type_notification_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
