# Generated by Django 4.2 on 2025-04-22 09:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('general', '0007_statusgroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusGroups',
            new_name='StatusGroup',
        ),
    ]
