# Generated by Django 4.2 on 2025-04-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_rename_statusgroups_statusgroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusgroup',
            name='group',
        ),
        migrations.AddField(
            model_name='statusgroup',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
