# Generated by Django 4.2 on 2025-04-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusgroup',
            name='status',
        ),
        migrations.AddField(
            model_name='statusgroup',
            name='status',
            field=models.ManyToManyField(related_name='group_status', to='general.status'),
        ),
    ]
