# Generated by Django 4.0 on 2025-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_jobidcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusgroup',
            name='status',
            field=models.ManyToManyField(related_name='group_status', to='general.Status'),
        ),
    ]
