# Generated by Django 4.0 on 2025-06-03 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_alter_statusgroup_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
