# Generated by Django 4.0 on 2025-03-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='natcorelease',
            name='firmware',
            field=models.CharField(default='2024-01-01', max_length=20),
            preserve_default=False,
        ),
    ]
