# Generated by Django 4.0 on 2025-03-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0002_natcorelease_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='natcorelease',
            name='build_version',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
