# Generated by Django 4.0 on 2025-03-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0003_natcorelease_build_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='natcorelease',
            name='firmware',
            field=models.CharField(max_length=50),
        ),
    ]
