# Generated by Django 4.2 on 2025-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stb", "0004_alter_natcorelease_firmware"),
    ]

    operations = [
        migrations.AlterField(
            model_name="natcorelease",
            name="release_type",
            field=models.CharField(
                choices=[("MR", "MR"), ("PAT", "PAT")],
                help_text="MR - Major Release",
                max_length=20,
            ),
        ),
    ]
