# Generated by Django 4.2 on 2025-04-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0006_natcofirmware_alter_natcorelease_firmware'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnatco',
            name='manufacture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stb.stbmanufacture'),
        ),
        migrations.RemoveField(
            model_name='natco',
            name='manufacture',
        ),
        migrations.AddField(
            model_name='natco',
            name='manufacture',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='stb.stbmanufacture'),
            preserve_default=False,
        ),
    ]
