# Generated by Django 4.2 on 2025-04-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0007_historicalnatco_manufacture_remove_natco_manufacture_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnatco',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical nat co', 'verbose_name_plural': 'historical nat cos'},
        ),
    ]
