# Generated by Django 4.0 on 2025-05-09 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0008_alter_historicalnatco_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnatco',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Natcos', 'verbose_name_plural': 'historical Natcos'},
        ),
        migrations.AlterModelOptions(
            name='natco',
            options={'permissions': [('view_natco_option', 'Can View natco Option List')], 'verbose_name': 'Natcos', 'verbose_name_plural': 'Natcos'},
        ),
        migrations.AlterField(
            model_name='historicalstbnodeconfig',
            name='natco',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stbnodeconfig',
            name='natco',
            field=models.CharField(max_length=200),
        ),
    ]
