# Generated by Django 4.0 on 2025-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0009_alter_historicalnatco_options_alter_natco_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstbnodeconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stbnodeconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
