# Generated by Django 4.0 on 2025-05-19 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0011_stbresults_stbtoken_stburl'),
    ]

    operations = [
        migrations.DeleteModel(
            name='STBResults',
        ),
    ]
