# Generated by Django 4.2 on 2025-05-21 06:06

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_comment_comments_and_more'),
        ('stb', '0012_delete_stbresults'),
    ]

    operations = [
        migrations.CreateModel(
            name='StbResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('result_id', models.CharField(max_length=255)),
                ('job_uid', models.CharField(max_length=255)),
                ('result_url', models.URLField()),
                ('triage_url', models.URLField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('error', 'Error')], max_length=10)),
                ('failure_reason', models.TextField(blank=True, default='', null=True)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.testcasescript')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
