# Generated by Django 4.0 on 2025-06-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('stb', '0013_stbresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='stbtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
