# Generated by Django 4.0 on 2025-06-12 04:37

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0015_stbapi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='natcorelease',
            options={'verbose_name': 'NatCo Releases', 'verbose_name_plural': 'NatCo Releases'},
        ),
        migrations.CreateModel(
            name='STBNodeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('natcos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='natcos', to='stb.natco')),
                ('stb_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='stb.stbnode')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
