# Generated by Django 4.0 on 2025-06-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0016_alter_natcorelease_options_stbnodemapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='natcorelease',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
