# Generated by Django 4.0 on 2025-06-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stb', '0017_natcorelease_friendly_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalstbnodeconfig',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical STB NodeConfigs', 'verbose_name_plural': 'historical STB NodeConfigs'},
        ),
        migrations.AlterModelOptions(
            name='natcofirmware',
            options={'verbose_name': 'Natco Firmware', 'verbose_name_plural': 'Natco Firmware'},
        ),
        migrations.AlterModelOptions(
            name='stbnodeconfig',
            options={'verbose_name': 'STB NodeConfigs', 'verbose_name_plural': 'STB NodeConfigs'},
        ),
    ]
